spring:
  application:
  datasource:
    url: jdbc:mysql://db-5308.cs.dal.ca/CSCI5308_2_DEVINT
    driver-class-name: org.h2.Driver
    username: ${DEVINT_DB_USER}
    password: ${DEVINT_DB_PASSWORD}
    platform: h2
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        security: DEBUG
        web: DEBUG
      hibernate:
        SQL: DEBUG

#If you want to use some other database other than H2, just change the config accordingly. ## DO NOT COMMIT YOUR CHANGED FILE
server:
  port: 8081
