spring:
  application:
  datasource:
    url: jdbc:mysql://db-5308.cs.dal.ca/CSCI5308_4_DEVINT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DEVINT_DB_USER}
    password: ${DEVINT_DB_PASSWORD}
    platform: h2
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        security: DEBUG
        web: DEBUG
      hibernate:
        SQL: DEBUG

#If you want to use some other database other than H2, just change the config accordingly. ## DO NOT COMMIT YOUR CHANGED FILE
server:
  port: 8081
