spring:
  datasource:
    url: jdbc:mysql://localhost:3306/neighbourly
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # Change to 'validate' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
